### ISSUE TITLE
Docker image is failed to be built

### ISSUE THREAD

**Issue by Ahmadrezauf** [SwissDataScienceCenter/renku#670]
Hi, 

I have pushed some changes to my repository and now I cannot create a docker image.

**Comment by ableuler** [comment]
Hi @Ahmadrezauf, 
and thanks for reporting this problem. If you provide a bit more context (maybe you can point us to the project?) we might be able to provide more help in finding out why the build is failing.

**Comment by Ahmadrezauf** [comment]
Hi, It is a private project named "Distance Testing." 
Before stopping the last notebook server, I have pushed everything that was updated. Maybe the problem is with syncing. Here is the pipeline review:
Running with gitlab-runner 12.2.0 (a987417a)
  on renkulab-runner-1TBdisk S25j9XrP
Using Docker executor with image docker:stable ...
Pulling docker image docker:stable ...
Using docker image sha256:b40e5afd78f53c1f0591358707e06ee7ca2778291dc53864fc1195fc7f3a011a for docker:stable ...
Running on runner-S25j9XrP-project-935-concurrent-0 via e78ef7c33048...
Fetching changes...
Reinitialized existing Git repository in /builds/gitlab/ahmadrezauf/distancetesting/.git/
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: unpack-objects failed
ERROR: Job failed: exit code 1

**Comment by ableuler** [comment]
> Fetching changes...
> Reinitialized existing Git repository in /builds/gitlab/ahmadrezauf/distancetesting/.git/
> error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
> fatal: the remote end hung up unexpectedly
> fatal: early EOF

That looks like a connectivity problem... Does the problem persist if you restart the build?

**Comment by Ahmadrezauf** [comment]
Yes.

**Comment by ableuler** [comment]
ok, it looks like you have accidentally committed a large amount of data to the repository instead of adding it to git-lfs. See [our docs](https://renku.readthedocs.io/en/latest/user/lfs.html) for info about data in renku and specifically [this documentation](https://github.com/git-lfs/git-lfs/wiki/Tutorial#migrating-existing-repository-data-to-lfs) on how to fix this.

**Comment by rokroskar** [comment]
@Ahmadrezauf this issue has been idle for some time - have you been able to resolve the problem?

**Comment by gavin-k-lee** [comment]
Closed for inactivity
